easy_admin:
    site_name: Kyokushin Rzeszów
    design:
      brand_color: '#de1b1b'
    entities:
      Category:
        label: 'Kategorie'
        class: AppBundle\Entity\Category
        list:
            fields:
                - { property: 'name', label: 'Nazwa kategorii'}
                - { property: 'posts', label: 'Powiązane posty'}
      Tag:
        label: 'Tagi'
        class: AppBundle\Entity\Tag
        form:
            fields:
                - { property: 'name', label: 'Nazwa tagu'}

      Post:
        label: 'Aktualności'
        class: AppBundle\Entity\Post
        list:
            fields:
                - id
                - { property: 'title', label: 'Tytuł' }
                - { property: 'author', label: 'Autor'}
                - { property: 'createDate', label: 'Data utworzenia' }
                - { property: 'publishedDate', label: 'Data opublikowania' }
                - { property: 'category', label: 'Powiązane kategorie' }
                - { property: 'tags', label: 'Tagi' }
        form:
            fields:
                - { property: 'title', label: 'Tytuł', type_options: { required: true } }
                - { property: 'content',type: 'ckeditor', label: 'Treść aktualności', type_options: { required: true } }
                - { property: 'publishedDate', help: 'Data publikacji (pojawienia się na stronie głównej aktulaności) fomrmat: Rok/miesiąć/dzien godzina/minuta', label: 'Data publikacji', type_options: { required: false } }
                - { property: 'category', label: 'Kategoria aktualności' }
                - { property: 'tags', label: 'Powiązane tagi' }
                - { property: 'author', label: 'Autor', type_options: { required: true }}
      User:
        label: 'Użytkownicy'
        class: AppBundle\Entity\User
      Photo:
        label: 'Zdjęcia'
        class: AppBundle\Entity\Photo
        list:
            fields:
                - { property: 'imageName', type: 'image', base_path: '%app.path.gallery_image%', label: 'Image' }
                - { property: 'slug' }
                - { property: 'imageSize', format: "%0.2f", label: 'Rozmiar (MB)' }
                - { property: 'gallery' }
                - { property: 'updatedAt' }
        form:
            fields:
                - { property: 'imageFile',type: AppBundle\Form\Type\CustomFileType, type_options: { required: true } }
                - { property: 'slug'}
                - { property: 'gallery' }

      Gallery:
        label: 'Galerie'
        class: AppBundle\Entity\Gallery
        list:
            fields:
                - { property: 'coverImagePhoto', type: 'image', base_path: '%app.path.gallery_image%', label: 'Image' }
                - "name"
                - "createdAt"
                - "photos"
        form:
            fields:
                - { property: 'name', label: 'Nazwa galerii'}
                - { property: 'description', label: 'Opis galerii'}
                - { property: 'coverImagePhoto', label: 'Okładka albumu zdjęć', type_options: { required: true } }
